<a href="https://colab.research.google.com/github/Harlequelrah/Learning_data_analysis/blob/main/Learning_data_analysis/Courses/Partie_2/quizz_exo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import pandas as pd
import numpy as np
data = pd.read_csv('https://raw.githubusercontent.com/Harlequelrah/Learning_data_analysis/refs/heads/main/Learning_data_analysis/data/quizz_exo.csv')
data.head()

   Position Sexe     Temps  Dept Temps_secondes   Age
0         1    M  00:32:23    76           1943  40.0
1         2    M  00:32:40    27           1960  34.0
2         3    M  00:33:15    76           1995  44.0
3         4    M  00:33:23    76           2003  46.0
4         5    M  00:33:29    76           2009  26.0

# Question 1
Sachant que l'ensemble des coureurs proviennent soit de la Seine-Maritime (76), soit de l'Eure (27) ou soit du Calvados (14), quel département n'appartenant pas à cette liste apparaît pourtant dans notre jeu de données ?

In [56]:
data.loc[~data['Dept'].isin([27,76,14])]
# C'est le département 18

     Position Sexe     Temps  Dept Temps_secondes   Age
21         22    M  00:36:22    78           2182  40.0
35         36    M  00:37:31    78           2251  42.0
74         75    M  00:42:06    78           2526  57.0
255       256    M  00:55:08    78           3308  42.0
289       290    F  00:59:09    78           3549  43.0

# Question 2

Notre jeu de données contient plusieurs valeurs manquantes. Déterminez combien exactement et combien de variables sont concernées :

In [57]:
data.isna().sum()
# 2 valeurs manquantes pour le sexe et 4 valeurs manquantes pour l'Age donc 6 variables manquantes sur 2 variables

Position          0
Sexe              2
Temps             0
Dept              0
Temps_secondes    0
Age               4
dtype: int64

# Question 3

Essayez de convertir la variable Temps dans un format adapté (datetime, par exemple). Vous obtiendrez normalement une valeur manquante, après transformation. À quoi est due cette valeur manquante ?

In [58]:
data['Temps'] = pd.to_datetime(data['Temps'],errors='coerce') # conversion
data['Temps'].isna().sum() # il  y a une variable manquante
# erreur d'irrégularité 54min47s était sa valeur avant la transformation , ses indices (250,2)

np.int64(1)

# Question 4

En regardant les variables quantitatives (Position, Age et Temps_secondes), combien d'outliers se trouvent dans notre jeu de données au total ?

In [59]:
data.loc[data['Position']>340] # on a un oulier pour Position qui a la valeur 2640

     Position Sexe               Temps  Dept Temps_secondes   Age
264      2640    M 2025-07-04 00:56:21    76           3381  51.0

In [60]:
data.loc[data['Age']>80] # on a un oulier pour Age qui a la valeur 174

     Position Sexe               Temps  Dept Temps_secondes    Age
302       303    M 2025-07-04 01:00:04    76           3604  174.0

In [61]:
data['Temps_secondes'] = pd.to_numeric(data['Temps_secondes'],errors='coerce')
data['Temps_secondes'].describe()  # au vu de la sortie on peut suspecter un outlier qui serait le max au vu du std et de la moyenne

count     339.000000
mean     2952.138643
std       514.965773
min      1943.000000
25%      2600.000000
50%      2936.000000
75%      3307.000000
max      4231.000000
Name: Temps_secondes, dtype: float64

In [62]:
data.loc[data['Temps_secondes']>4000,'Temps_secondes'] # on a un oulier pour Temps_seconde qui a la valeur 4231.0
# on a au total 3 outliers

331    4014.0
332    4018.0
333    4087.0
334    4109.0
335    4114.0
336    4116.0
337    4171.0
338    4171.0
339    4231.0
Name: Temps_secondes, dtype: float64

# Question 5

Notre jeu de données possède-t-il des doublons, soit des personnes ayant la même position et le même temps à l'arrivée, avec les mêmes caractéristiques ?

In [64]:
data.loc[data[['Position','Temps_secondes']].duplicated(keep=False)] # Pas de doublon

Empty DataFrame
Columns: [Position, Sexe, Temps, Dept, Temps_secondes, Age]
Index: []

# Question 6

Après avoir vérifié tout cela, il reste encore une erreur dans notre jeu de données. Quelle est-elle ?

In [67]:
data.loc[~data['Sexe'].isin(['F','M'])] # Erreur lexicale sur Sexe qui contient O

     Position Sexe               Temps  Dept  Temps_secondes   Age
93         94    O 2025-07-04 00:43:46    76          2626.0  18.0
109       110  NaN 2025-07-04 00:44:39    27          2679.0  53.0
167       168    O 2025-07-04 00:48:53    76          2933.0  24.0
291       292  NaN 2025-07-04 00:59:16    27          3556.0  66.0